# Generated by Django 5.1 on 2025-04-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchdocument',
            name='file',
            field=models.FileField(upload_to='uploads/research_papers/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='researchdocument',
            name='file_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='researchdocument',
            name='file_size',
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='researchdocument',
            name='file_type',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='researchdocument',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
