# Generated by Django 5.1 on 2025-04-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_alter_researchdocument_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchdocument',
            name='file_hash',
        ),
        migrations.RemoveField(
            model_name='researchdocument',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='researchdocument',
            name='file_type',
        ),
        migrations.AlterField(
            model_name='researchdocument',
            name='keywords',
            field=models.TextField(help_text="put between each tow keywords ',' without any spaces"),
        ),
    ]
