# Generated by Django 5.1 on 2025-04-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_remove_researchdocument_file_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchdocument',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
